/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

module.exports = {
	aws_project_region: 'us-east-1',
	aws_cognito_identity_pool_id:
		'us-east-1:f16848ad-bbb1-4ffc-93ac-13c0284b9953',
	aws_cognito_region: 'us-east-1',
	aws_user_pools_id: 'us-east-1_cQnW7Uycq',
	aws_user_pools_web_client_id: '3q5dmpqih7mkvsep88a3j2uvo2',
	oauth: {
		domain: 'trava-prod.auth.us-east-1.amazoncognito.com',
		scope: [
			'phone',
			'email',
			'openid',
			'profile',
			'aws.cognito.signin.user.admin',
		],
		redirectSignIn: 'trava://',
		redirectSignOut: 'trava://',
		responseType: 'code',
	},
	federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
	aws_cognito_username_attributes: [],
	aws_cognito_social_providers: ['FACEBOOK', 'GOOGLE', 'APPLE'],
	aws_cognito_signup_attributes: ['EMAIL'],
	aws_cognito_mfa_configuration: 'OPTIONAL',
	aws_cognito_mfa_types: ['SMS'],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [
			'REQUIRES_LOWERCASE',
			'REQUIRES_UPPERCASE',
			'REQUIRES_NUMBERS',
			'REQUIRES_SYMBOLS',
		],
	},
	aws_cognito_verification_mechanisms: ['EMAIL'],
	aws_appsync_graphqlEndpoint:
		'https://md6aoumzf5enrlp3v4h6vo5ydy.appsync-api.us-east-1.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-1',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
	aws_user_files_s3_bucket: 'trava-storage125455-prod',
	aws_user_files_s3_bucket_region: 'us-east-1',
}
