/* eslint camelcase: 0 */

export enum DateFormat {
  D_MMMM_YYYY = 'D MMMM YYYY',
  MMM_D_YY = 'MMM D, YY',
  MMM_DD_YYYY = 'MMM DD, YYYY',
  MMMM_YYYY = 'MMMM, YYYY',
  MMMM_DD_YYYY = 'MMMM DD, YYYY',
  YYYY_MM_DD = 'YYYY-MM-DD',
  D = 'D',
  MMMM = 'MMMM',
  YYYY = 'YYYY',
  MMMM_D_YYYY = 'MMMM D, YYYY',
  MMM_DO_YYYY = 'MMM Do, YYYY',
  YYYYMMDD = 'YYYYMMDD',
  MMMM_D = 'MMMM D',
  dddd = 'dddd',
  ddd = 'ddd',
  dddd_MMMM_Do = 'dddd, MMMM Do',
  ddd_MMMM_Do = 'ddd, MMMM Do',
  dddd_MMM_D = 'dddd, MMM D',
  MMM_D_YYYY = 'MMM D, YYYY',
  ddd_MMM_D_z = 'ddd, MMM D z',
  hh_mm = 'hh:mm',
  A = 'A',
  hh_mm_A = 'hh:mm A',
  ddd_MMM_D = 'ddd, MMM D',
  dddd_MMMM_D = 'dddd, MMMM D',
  HHmm = 'HHmm',
  hh_mm_A_z = 'hh:mm A z',
  z = 'z',
  MMM = 'MMM',
  YYYYMMDDTHHmmss = 'YYYY-MM-DDTHH:mm:ss.SSS',
}
