"use strict";
/* eslint camelcase: 0 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DateFormat = void 0;
var DateFormat;
(function (DateFormat) {
    DateFormat["D_MMMM_YYYY"] = "D MMMM YYYY";
    DateFormat["MMM_D_YY"] = "MMM D, YY";
    DateFormat["MMM_DD_YYYY"] = "MMM DD, YYYY";
    DateFormat["MMMM_YYYY"] = "MMMM, YYYY";
    DateFormat["MMMM_DD_YYYY"] = "MMMM DD, YYYY";
    DateFormat["YYYY_MM_DD"] = "YYYY-MM-DD";
    DateFormat["D"] = "D";
    DateFormat["MMMM"] = "MMMM";
    DateFormat["YYYY"] = "YYYY";
    DateFormat["MMMM_D_YYYY"] = "MMMM D, YYYY";
    DateFormat["MMM_DO_YYYY"] = "MMM Do, YYYY";
    DateFormat["YYYYMMDD"] = "YYYYMMDD";
    DateFormat["MMMM_D"] = "MMMM D";
    DateFormat["dddd"] = "dddd";
    DateFormat["ddd"] = "ddd";
    DateFormat["dddd_MMMM_Do"] = "dddd, MMMM Do";
    DateFormat["ddd_MMMM_Do"] = "ddd, MMMM Do";
    DateFormat["dddd_MMM_D"] = "dddd, MMM D";
    DateFormat["MMM_D_YYYY"] = "MMM D, YYYY";
    DateFormat["ddd_MMM_D_z"] = "ddd, MMM D z";
    DateFormat["hh_mm"] = "hh:mm";
    DateFormat["A"] = "A";
    DateFormat["hh_mm_A"] = "hh:mm A";
    DateFormat["ddd_MMM_D"] = "ddd, MMM D";
    DateFormat["dddd_MMMM_D"] = "dddd, MMMM D";
    DateFormat["HHmm"] = "HHmm";
    DateFormat["hh_mm_A_z"] = "hh:mm A z";
    DateFormat["z"] = "z";
    DateFormat["MMM"] = "MMM";
    DateFormat["YYYYMMDDTHHmmss"] = "YYYY-MM-DDTHH:mm:ss.SSS";
})(DateFormat || (exports.DateFormat = DateFormat = {}));
